apiVersion: apps/v1
kind: Deployment
metadata:
  name: mario-game
  labels:
    run: mario-game
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mario-game
  template:
    metadata:
      labels:
        app: mario-game
    spec:
      containers:
      - image: pengbai/docker-supermario
        name: mario-game
        ports:
          - containerPort: 8080
            protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: mario-game
spec:
  type: LoadBalancer
  ports:
    - nodePort: 31000
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: mario-game
